### ISSUE TITLE
request.js doesn't properly handle secrets when uncommenting tutorial 6 

### ISSUE THREAD

**Issue by hudsonhrh** [dwightjl/functions-examples#1]
it says No secrets URL. ensure api key was properly being passed in from the .env.enc

**Comment by dwightjl** [comment]
Working on a solution for this.

**Comment by dwightjl** [comment]
Secrets support is added, but not yet documented. The code is available in the https://github.com/smartcontractkit/smart-contract-examples/tree/main/add-functions-to-project repository.
